third_project/my_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from my_app import views

# Template Tagging
app_name = 'my_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^testpage/$', views.test, name='test_page'),
    url(r'^register/$', views.register, name='registration'),
    url(r'^user_login/$', views.user_login, name='user_login')
]

third_project/third_project/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import url, include
from my_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^my_app/', include('my_app.urls')),
    url(r'$', views.index, name='index'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special')

]

third_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional attr
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

third_project/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

third_project/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm, UserProfileInfoForm

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    random_dict = {'name': 'Sourabh Majumdar'}
    return render(request, 'my_app/index.html', context=random_dict)


@login_required
def special(request):
    return HttpResponse("You are logged in, Nice !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def test(request):

    return render(request, 'my_app/test.html')


def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors)
            print(profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'my_app/registration.html', context={
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:

                return HttpResponse(" ACCOUNT NOT ACTIVE ")
        else:
            print("Someone tried to login and failed ")
            print("Username : {} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied ")

    else:
        return render(request, 'my_app/login.html')

third_project/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">

        <div class="container">

            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Django</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'my_app:registration'%}">Register</a></li>

                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'my_app:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block  %}
        <!-- Anything outsied this will be inherited if you extend  -->
        {% endblock %}
    </div>
</body>
</html>

third_project/templates/my_app/index.html
<!DOCTYPE html>
{% extends 'my_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Welcome to Mojo-App</h1>
    </div>
{% endblock %}

third_project/templates/my_app/login.html
{% extends 'my_app/base.html'%}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'my_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username :</label>
        <input type="text" name="username" id="username" placeholder="Enter Username :">

        <label for="password">Password :</label>
        <input type="password" name="password" id="password">

        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

third_project/templates/my_app/registration.html
{% extends 'my_app/base.html' %}
{% load static %}
{% block body_block%}
<div class="jumbotron">
    {% if registered %}
    <h1> Thanks you for registering </h1>
    {% else %}
    <h1> Register Here</h1>
    <h3> Please fill out the form </h3>
    <form enctype="multipart/form-data" action="" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}

third_project/templates/my_app/test.html
<!DOCTYPE html>
{% extends "my_app/base.html" %}
{% block body_block %}

<h1>This is just a test page</h1>
{% endblock %}